---
deployment:
  tasks:
    - export DEPLOYPATH=/home/eternity/public_html/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /usr/bin/rsync -rlptD --exclude='.git/' --exclude='.cpanel.yml' --exclude='.ftpquota' --exclude='error_log' --exclude='compare_results.txt' --exclude='local_pre_restore_*.tgz' --exclude='system/database.php' --exclude='system/settings.php' --exclude='avatar/' --exclude='cover/' --exclude='upload/' --exclude='music/' --exclude='room_icon/' --exclude='gift/' --exclude='theme_public/' --exclude='goofy/' --exclude='updates files/update*' ./ "$DEPLOYPATH"
